name: Deploy to AWS ECR and ECS

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up the TAG environment variable
        run: echo "TAG=$(git rev-parse --short=4 HEAD)" >> $GITHUB_ENV

      - name: Output Tag Value
        run: echo "$TAG"

      # Set up AWS credentials (Make sure you add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as secrets in your GitHub repo)
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 135581164469.dkr.ecr.us-east-1.amazonaws.com

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t andre/andreapp3 .

      # Tag the image for ECR
      - name: Tag docker image with $TAG
        run: |
          echo "Tagging image with $TAG"
          docker tag andre/andreapp3:latest 135581164469.dkr.ecr.us-east-1.amazonaws.com/andre/andre:ecsimage$TAG

      # Push the Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          echo "Pushing image to ECR"
          docker push 135581164469.dkr.ecr.us-east-1.amazonaws.com/andre/andre:ecsimage$TAG


      # # Update ECS Task Definition
      # - name: Update ECS Task Definition
      #   run: |
      #     # Register a new task definition with the updated image
      #     aws ecs register-task-definition \
      #       --family my-ecs-task \
      #       --container-definitions "[{
      #         \"name\": \"dockergs\",
      #         \"image\": \"docker tag andre/andreapp3:latest 135581164469.dkr.ecr.us-east-1.amazonaws.com/andre/andreapp3$TAG\",
      #         \"cpu\": 256,
      #         \"memory\": 512,
      #         \"essential\": true,
      #         \"portMappings\": [{\"containerPort\": 8080, \"hostPort\": 8080, \"protocol\": \"tcp\"}]
      #       }]"

      # # Update ECS service to use the new task definition
      # - name: Update ECS service
      #   run: |
      #     aws ecs update-service \
      #       --cluster your-cluster-name \
      #       --service your-service-name \
      #       --task-definition my-ecs-task
